
import React, { useState, useCallback } from 'react';
import { ConversionOptions, InputFileType, OutputFileType } from './types';
import { generateConversionScript } from './services/geminiService';
import Header from './components/Header';
import FileUpload from './components/FileUpload';
import ConversionOptionsPanel from './components/ConversionOptionsPanel';
import ResultDisplay from './components/ResultDisplay';
import Loader from './components/Loader';

const App: React.FC = () => {
    const [inputFile, setInputFile] = useState<File | null>(null);
    const [generatedScript, setGeneratedScript] = useState<string>('');
    const [isLoading, setIsLoading] = useState<boolean>(false);
    const [error, setError] = useState<string | null>(null);

    const handleFileChange = (file: File | null) => {
        if (file) {
            setInputFile(file);
            setGeneratedScript('');
            setError(null);
        }
    };

    const handleGenerateScript = useCallback(async (options: ConversionOptions, inputType: InputFileType, outputTypes: OutputFileType[]) => {
        if (!inputFile) {
            setError("Please upload a file first.");
            return;
        }

        setIsLoading(true);
        setError(null);
        setGeneratedScript('');

        try {
            const script = await generateConversionScript(inputFile.name, inputType, outputTypes, options);
            setGeneratedScript(script);
        } catch (e) {
            console.error(e);
            setError("Failed to generate script. Please check your API key and try again.");
        } finally {
            setIsLoading(false);
        }
    }, [inputFile]);

    const handleReset = () => {
        setInputFile(null);
        setGeneratedScript('');
        setError(null);
        setIsLoading(false);
    };

    return (
        <div className="min-h-screen bg-gray-900 text-gray-100 flex flex-col items-center p-4 sm:p-6 lg:p-8">
            <div className="w-full max-w-4xl mx-auto">
                <Header />
                <main className="mt-8 space-y-8">
                    {generatedScript && (
                        <div className="text-center">
                            <button
                                onClick={handleReset}
                                className="bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded-lg transition-colors duration-300"
                            >
                                Start Over
                            </button>
                        </div>
                    )}
                    
                    {!generatedScript && !isLoading && (
                        <div className="bg-gray-800 p-6 rounded-xl shadow-lg border border-gray-700 space-y-6">
                            <FileUpload onFileChange={handleFileChange} currentFile={inputFile} />
                            {inputFile && (
                                <ConversionOptionsPanel
                                    onGenerate={handleGenerateScript}
                                    isLoading={isLoading}
                                />
                            )}
                        </div>
                    )}

                    {isLoading && <Loader />}
                    
                    {error && (
                        <div className="bg-red-900/50 border border-red-700 text-red-300 p-4 rounded-lg text-center">
                            <p className="font-semibold">Error</p>
                            <p>{error}</p>
                        </div>
                    )}

                    {generatedScript && (
                        <ResultDisplay script={generatedScript} />
                    )}

                    <footer className="text-center text-gray-500 text-sm mt-12 pb-4">
                        <p>Generated by a world-class frontend React engineer with Gemini API.</p>
                        <p>This tool generates scripts but does not execute them. Always review scripts before running them locally.</p>
                    </footer>
                </main>
            </div>
        </div>
    );
};

export default App;
